{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flyte-proxy.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "flyte-proxy.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels: {{- include "flyte-proxy.proxySelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "flyte-proxy.proxySelectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: proxy
          {{- with .Values.image }}
          image: {{ printf "%s:%s" .repository .tag | quote }}
          imagePullPolicy: {{ .pullPolicy | quote }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8000
          volumeMounts:
            - name: config
              mountPath: /etc/envoy
            # - name: tls-certs
            #   readOnly: true
            #   mountPath: /certs
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 30
          readinessProbe:
            tcpSocket:
              port: http
      volumes:
        - name: config
          configMap:
            name: {{ include "flyte-proxy.proxyConfigMapName" . }}
        # - name: tls-certs
        #   secret:
        #     secretName: secret-tls-flyte-proxy
{{- end }}
